<a href="https://colab.research.google.com/github/neeshat/Data-Science/blob/main/Seventh_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Installing and importing required libraries**

In [55]:
!pip install pandas numpy scikit-learn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# **Connecting Google Drive with Colab and loading the dataset**

In [56]:
from google.colab import drive
drive.mount('/content/drive')
import warnings
warnings.filterwarnings('ignore')

# TODO: Load the housing data

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/datasets/Housing.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **Performing Tasks**

In [57]:
# TODO: How many houses are there?

print(f"The number of houses: {df.shape[0]}")

# TODO: Showing first 3 houses

print("\nFirst three houses are below: ")
df.head(3)

The number of houses: 545

First three houses are below:

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished

In [58]:
# TODO: Showing all column names

print("Columns: ", df.columns.tolist())

# TODO: Showing data types of all columns

print("\nShowing data types of all columns: ")
print(df.dtypes)

Columns:  ['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea', 'furnishingstatus']

Showing data types of all columns:
price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

In [59]:
#Converting Yes/No to 1/0 - Using LabelEncoder; Since there are 2 categories


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cols_to_convert = ['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea']
for col in cols_to_convert:
  df[col] = le.fit_transform(df[col])

# Using One-Hot Encoding on furnishingstatus - Since, there are more than 2 categories

df = pd.get_dummies(df, columns=['furnishingstatus'], drop_first = True)

In [60]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,False,False
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,False,False
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,True,False
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,False,False
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,False,False

In [62]:
# Check what's in our data

print("Current mainroad values:\n", df['mainroad'].head())

Current mainroad values:
 0    1
1    1
2    1
3    1
4    1
Name: mainroad, dtype: int64

In [64]:
# Split into Train and Test
# TODO: Split - 80% train, 20% test

X = df.drop('price', axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)

In [72]:
#Apply StandardScaler
# Area is huge (1650-13300), Bedrooms is small (1-6)!


print(f"Min Area is: ", X_train['area'].min())
print(f"Max Area is: ", X_train['area'].max())

print(f"Min bedrooms: ", X_train['bedrooms'].min())
print(f"Max bedrooms: ", X_train['bedrooms'].max())

Min Area is:  1650
Max Area is:  16200
Min bedrooms:  1
Max bedrooms:  6

In [74]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [90]:
# After Scaling

X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_train_scaled_df

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,-0.400969,-1.333921,-0.562749,-0.920575,0.414781,-0.463125,-0.746420,-0.219265,1.509369,1.556577,-0.552620,1.159347,-0.691351
1,-0.300229,-1.333921,-0.562749,-0.920575,-2.410913,-0.463125,-0.746420,-0.219265,-0.662528,-0.783656,-0.552620,1.159347,-0.691351
2,-0.542921,-2.712095,-0.562749,-0.920575,-2.410913,-0.463125,-0.746420,-0.219265,-0.662528,-0.783656,-0.552620,-0.862554,1.446443
3,0.853700,0.044253,-0.562749,-0.920575,0.414781,-0.463125,1.339728,-0.219265,1.509369,1.556577,1.809561,1.159347,-0.691351
4,5.057298,2.800602,3.362989,0.259927,0.414781,-0.463125,-0.746420,-0.219265,-0.662528,-0.783656,-0.552620,-0.862554,1.446443
...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,-0.155988,-1.333921,-0.562749,-0.920575,0.414781,-0.463125,-0.746420,-0.219265,1.509369,-0.783656,1.809561,1.159347,-0.691351
432,0.533622,0.044253,-0.562749,0.259927,0.414781,-0.463125,1.339728,-0.219265,1.509369,0.386461,-0.552620,-0.862554,-0.691351
433,-1.488501,2.800602,-0.562749,0.259927,-2.410913,-0.463125,1.339728,-0.219265,-0.662528,-0.783656,-0.552620,1.159347,-0.691351
434,-0.368000,1.422428,-0.562749,0.259927,-2.410913,-0.463125,-0.746420,-0.219265,-0.662528,0.386461,-0.552620,-0.862554,1.446443
435,1.416927,0.044253,-0.562749,-0.920575,0.414781,-0.463125,-0.746420,-0.219265,-0.662528,1.556577,-0.552620,-0.862554,-0.691351

# **Training and testing the model**

In [104]:
# Model Training

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_scaled, y_train)

train_score = model.score(X_train_scaled, y_train)
print(f"Traning accuracy: {train_score:.1%}")

test_score = model.score(X_test_scaled, y_test)
print(f"Testing accuracy: {test_score:.1%}")

Traning accuracy: 67.8%
Testing accuracy: 67.6%

In [112]:
# Performing 5 fold cross validation

from sklearn.model_selection import cross_val_score
score = cross_val_score(model, X_train_scaled, y_train, cv=5)
for i in range(5):
  print(f"Test {i+1} score: {score[i]:.1%}")
print(f"Accuracy of the model is: {score.mean():.1%}")

Test 1 score: 66.1%
Test 2 score: 71.1%
Test 3 score: 62.4%
Test 4 score: 63.0%
Test 5 score: 62.6%
Accuracy of the model is: 65.0%

In [117]:
# Predict a House Price
# New house details:
# area=5000, bedrooms=3, bathrooms=2, stories=2,
# mainroad=yes, guestroom=no, basement=yes,
# hotwaterheating=no, airconditioning=yes,
# parking=2, prefarea=yes, furnishingstatus=furnished
#your code here

new_house_data = pd.DataFrame({
    'area': [5000],
    'bedrooms': [3],
    'bathrooms': [2],
    'stories': [2],
    'mainroad': [1],
    'guestroom': [0],
    'basement': [1],
    'hotwaterheating': [0],
    'airconditioning': [1],
    'parking': [2],
    'prefarea': [1],
    'furnishingstatus_semi-furnished': [0],
    'furnishingstatus_unfurnished': [0]

})

new_house_data = scaler.transform(new_house_data)
new_house_data

array([[-0.07127511,  0.0442533 ,  1.40011987,  0.25992695,  0.41478068,
        -0.46312491,  1.33972825, -0.2192645 ,  1.50936924,  1.55657729,
         1.80956067, -0.86255435, -0.69135093]])

In [126]:
new_house_price = model.predict(new_house_data)
print(f"Predicted new house price is: {new_house_price[0]}")

Predicted new house price is: 7262684.607641466